remote_theme: pages-themes/midnight@v0.2.0
title: GitHub Pages
description: ROBOTICALLY OBNOXIOUS SERVING ASSISTANT - An emotional smart assistant that doesnt listen to you

show_downloads: [true]
github:
  zip_url: https://api.github.com/repos/Cornelius-Figgle/ROSA/releases/latest
  tar_url: https://api.github.com/repos/Cornelius-Figgle/ROSA/releases/latest
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
