remote_theme: "mmistakes/minimal-mistakes@4.24.0" #pages-themes/midnight@v0.2.0
title: ROSA - Info Site
description: ROBOTICALLY OBNOXIOUS SERVING ASSISTANT - An emotional smart assistant that doesnt listen to you

minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"
show_downloads: [true]
github:
  zip_url: https://github.com/cornelius-figgle/ROSA/releases
  tar_url: https://github.com/cornelius-figgle/ROSA/releases
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache
