[tool.poetry]
name = "ROSA"
version = "0.5.0"
description = "ROBOTICALLY OBNOXIOUS SERVING ASSISTANT - an emotional voice assistant"
authors = ["Cornelius-Figgle <max@fullimage.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
SpeechRecognition = "^3.9.0"
pygame = "2.1.3.dev8"
PyAudio = "^0.2.13"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.7.0"
pywin32 = "^305"
pywin32-ctypes = "^0.2.0"
PyQt5 = "^5.15.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
